### ISSUE TITLE
Serverless workflows support

### ISSUE THREAD

**Issue by mcopik** [spcl/serverless-benchmarks#60]
We're starting to add support for serverless workflows.

- [ ] Implementation of generic state machine 
- [x] Generation of AWS Step config (#55)
- [ ] Generation of Azure Durable config
- [ ] Benchmarks
  - [ ] Clear up code from #47 
  - [ ] Clear up code from #53

**Comment by mcopik** [comment]
Closing in favor of #88
